apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-app-first
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:TeeradonNamkanisorn/idp-app.git
    targetRevision: main
    path: platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
