apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set-manifests
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: "https://kubernetes.default.svc"
          - cluster: sut
            url: "https://kubernetes.default.svc"
  template:
    metadata:
      name: "{{cluster}}-manifest"
    spec:
      project: default
      source:
        repoURL: git@github.com:TeeradonNamkanisorn/nonprod-k8s-manifests.git
        path: "{{cluster}}/my-app/cart"
        targetRevision: main
      destination:
        server: "{{url}}"
        namespace: default
      # syncPolicy:
      #   automated:
      #     prune: true
      #     allowEmpty: true
      #     selfHeal: true
