apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-b
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Team B
  destinations:
    - name: "*"
      namespace: "dev-app"
      server: "https://kubernetes.default.svc"
  # clusterResourceWhitelist:
  #   - group: ""
  #     kind: Namespace
  roles:
    - description: Read Only
      name: read-only
      policies:
        - p, proj:team-b:read-only, applications, get, team-b/*, allow
    - description: Read Write
      name: read-write
      policies:
        - p, proj:team-b:read-write, applications, get, team-b/*, allow
        - p, proj:team-b:read-write, applications, sync, team-b/*, allow
        - p, proj:team-b:read-write, applications, update, team-b/*, allow
  sourceRepos:
    - git@github.com:TeeradonNamkanisorn/nonprod-k8s-manifests.git
